# Generated by Django 3.2.6 on 2021-08-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to='visitors.profile')),
                ('staff_members', models.ManyToManyField(related_name='staff_member', to='visitors.Profile')),
            ],
        ),
    ]
