# Generated by Django 3.2.6 on 2021-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0010_alter_contact_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='authur',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
