# Generated by Django 3.2.6 on 2021-08-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0012_alter_review_authur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='authur',
            field=models.CharField(max_length=50),
        ),
    ]
