# Generated by Django 3.2.6 on 2021-08-26 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0013_alter_review_authur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='authur',
        ),
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to='visitors.profile'),
        ),
    ]
